// Generated by codegen/vm_predef_atoms_*.py

namespace gluon {
namespace atom {

extern const char *g_predef_atoms;

const char *g_predef_atoms =
  "\x08"  "badmatch"
  "\x05"  "error"
  "\x04"  "exit"
  "\x05"  "false"
  "\x05"  "throw"
  "\x04"  "true"
  "\x01"  "-"
  "\x06"  "length"
  ;

} // ns atom
} // ns gluon

