// Generated by codegen/vm_predef_atoms_*.py

namespace gluon {
namespace atom {

extern const char *g_predef_atoms;

const char *g_predef_atoms =
  "\x04"  "true"
  "\x05"  "false"
  ;

} // ns atom
} // ns gluon

