#!/usr/bin/python
# takes: genop.tab from erlang/otp
# produces: source of predef atoms on vm boot
import libgenop

libgenop.load()

print("""// Generated by codegen/vm_predef_atoms_*.py

namespace gluon {
namespace atom {

extern const char *g_predef_atoms;
""")

# print atom constants
print("const char *g_predef_atoms =")
for a in libgenop.atom_tab:
    print('  "\\x%02x"  "%s"' % (len(a['atom']), a['atom']))

print("""  ;

} // ns atom
} // ns gluon
""")
