#!/usr/bin/python
# takes: genop.tab from erlang/otp
# produces: predef atoms include file with constants
import libgenop

libgenop.load()

print("""// Generated by codegen/vm_predef_atoms_*.py

#include "g_term.h"

namespace gluon {
namespace atom {
""")

# print atom constants
for a in libgenop.atom_tab:
    constname = libgenop.atom_constname(a)
    print("  const Term %s = Term::make_atom(%d);" % (constname, a['id']))

print("""
  extern const char *g_predef_atoms;

} // ns atom
} // ns gluon
""")
