#!/usr/bin/python
# takes: genop.tab from erlang/otp
# produces: sorted bif search table
import libgenop

libgenop.load()

print("""// Generated by codegen/vm_bif_tab_*.py
#include "g_defs.h"
#include "g_term.h"

namespace gluon {
namespace bif {

typedef struct {
  Term   fun;
  word_t arity;
  void   *bif_fn;
} bif_index_t;

""")

print("const word_t BIF_TABLE_SIZE = %d;" % len(libgenop.bif_tab));

print("""extern const bif_index_t g_bif_table[BIF_TABLE_SIZE];

} // ns bif
} // ns gluon
""")
