#!/usr/bin/python
# takes: genop.tab from erlang/otp
# produces: sorted bif search table
import libgenop

libgenop.load()

print("""// Generated by codegen/vm_bif_tab_*.py
#include "g_defs.h"
#include "g_term.h"

namespace gluon {
namespace bif {

typedef struct {
  Term fun;
  Word arity;
  void *bif_fn;
} BIFIndex;

""")

print("const Word bif_table_size = %d;" % len(libgenop.bif_tab));

print("""extern const BIFIndex g_bif_table[bif_table_size];

} // ns bif
} // ns gluon
""")
