#!/usr/bin/python
# takes: genop.tab from erlang/otp
# produces: g_jump_table includable file with label pointer table for vm ops
import libgenop

ops = libgenop.load()

print("// Generated by codegen/vm_jump_table.py")
print

# make op map by opcode
ops_by_code = {}
for op in ops:
    ops_by_code[op['opcode']] = op

# print arity map
print("const void *VM::g_opcode_labels[] = { nullptr, // no 0 opcode")
for opcode in range(libgenop.MIN_OPCODE, libgenop.MAX_OPCODE+1):
    op = ops_by_code[opcode]
    print("    blockaddress(@VM::vm_loop, %%OP_%s), // opcode: %d" % (op['name'], opcode))
print("};")
print
